name: build-and-publish--clientSdk

on:
  push:
    branches: ['staging', "CI/CD_test"]
  workflow_dispatch:
  pull_request:
    branches: ['staging']
    types:
      [opened, closed]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set environment files
        run: |
          pushd packages/biconomy/nextJs
          echo "API_KEY=${{ secrets.BICONOMY_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          popd

          pushd packages/stackup/nextJs
          echo "API_KEY=${{ secrets.STACKUP_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          popd

          pushd packages/pimlico/nextJs
          echo "API_KEY=${{ secrets.PIMLICO_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          popd

          pushd packages/zerodev/nextJs
          echo "API_KEY=${{ secrets.ZERODEV_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          popd

          pushd packages/alchemy/nextJs
          echo "API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env
          popd

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/silence-laboratories/mpc-auth-client:staging

  pull_and_deploy:
    runs-on: mpc-account-abstraction-sdk-stage-deployer-asia
    needs: build-and-push
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: docker pull ghcr.io/silence-laboratories/mpc-auth-client:staging
      - run: docker compose -f compose-stage.yml up -d 

          
