name: build-and-publish--biconomy-and-stackup

on:
  push:
    branches: ['staging', 'CI/CD']
  # we can also trigger manually in case needed
  workflow_dispatch:
  pull_request:
    branches: ['staging']
    types:
      [closed]
jobs:
  build:
    runs-on: mpc-account-abstraction-sdk-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm i
          pushd packages/mpc
          npm run test
          npm run build
          popd
          pushd packages/biconomy/nextJs 
          echo "API_KEY=${{ secrets.BICONOMY_API_KEY }}" >> .env
          echo "NODE_ENV=development" >> .env 
          npm run build
          popd 
          pushd packages/stackup/nextJs
          echo "API_KEY=${{ secrets.STACKUP_API_KEY }}" >> .env
          echo "NODE_ENV=development" >> .env 
          npm run build
          popd

      - name: Build artifact
        run: |
          /usr/bin/7z a ./biconomy-stackup.7z ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: biconomy-stackup
          path: ./biconomy-stackup.7z
          
  deploy-staging:
    runs-on: mpc-account-abstraction-sdk-stage-deployer-asia
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: biconomy-stackup
          path: ./
      - run: |
            if [ -d "/opt/service/update" ]; then rm -Rf /opt/service/update; fi 
            mkdir /opt/service/update/
            mv ./biconomy-stackup.7z /opt/service/update/
            cd /opt/service/update/ && 7z x biconomy-stackup.7z
            cd /opt/service/update && npm i

      - run: |
            if [ -d "/opt/service/biconomy" ]; then rm -Rf /opt/service/biconomy; fi
            mv /opt/service/update/packages/biconomy/nextJs /opt/service/biconomy
            ln -sf /opt/service/update/node_modules /opt/service/biconomy/node_modules
      - run: |
            if [ -d "/opt/service/stackup" ]; then rm -Rf /opt/service/stackup; fi
            mv /opt/service/update/packages/stackup/nextJs /opt/service/stackup
            ln -sf /opt/service/update/node_modules /opt/service/stackup/node_modules
      - run: sudo systemctl restart biconomy.service stackup.service

          
