name: build-and-publish--clientSdk

on:
  push:
    branches: ['stage']
  workflow_dispatch:
  pull_request:
    branches: ['stage']
    types:
      [opened, closed]
jobs:
  build:
    #if: ${{ github.event.action }} == 'opened'
    runs-on: mpc-account-abstraction-sdk-stage-deployer-asia
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm i
          pushd packages/mpc
          npm run test
          npm run build
          popd
          pushd packages/biconomy/nextJs 
          echo "API_KEY=${{ secrets.BICONOMY_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          npm run build
          popd 
          pushd packages/stackup/nextJs
          echo "API_KEY=${{ secrets.STACKUP_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          npm run build
          popd
          pushd packages/pimlico/nextJs
          echo "API_KEY=${{ secrets.PIMLICO_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          npm run build
          popd
          pushd packages/zerodev/nextJs
          echo "API_KEY=${{ secrets.ZERODEV_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env 
          npm run build
          popd
          pushd packages/alchemy/nextJs
          echo "API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_SDK_MODE=development" >> .env
          npm run build
          popd
          if [ -d "/opt/service/mpc-auth-client" ]; then rm -Rf mpc-auth-client; fi 
          cp -r ../mpc-auth-client /opt/service/
      - run: sudo systemctl restart biconomy.service stackup.service pimlico.service zerodev.service alchemy.service

          
